title: Parenthood Journey
email: timandjunfamily@gmail.com
description: >
  Tim and Jun Surrogacy Journey.
baseurl: "" 
url: "" 
github_username:  tjdfamily

author: Copyright &copy; 2023
lang: en_US

# Build settings
safe: true 
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/